Sprint 3
Danilov-Andrey/middle.messenger.praktikum.yandex pull request #3
Opened 2022-04-24 20:34 UTC by Danilov-Andrey

Привет!
Добавил функционал как по тз, только к сожалению не добавил вывод/обработку ошибок (сделаю чуть позже).
И не сделал обновление списка чатов, смутило что компонент "моргает" - с этим тоже позже разберусь.

2022-04-25 09:08 UTC, podlovchenko requested changes
Привет!) Есть немного замечаний

1. После регистрации нужен редирект на страницу чатов (сейчас пользователь попадает на страницу авторизации, но ответ от сервера `User already in system`)
2. При обновлении страницы `Page Not Found` на netlify
3. Попробуй выполнить команду tsc и исправить ошибки типов
4. Часто едет форматирование, где-то используются одинарные кавычки, где-то двойные, также с `;`, приведи, пожалуйста в порядок код

Круто, что для веб сокетов сделал отдельный класс) Поправь конфликты и жду правок

2022-04-25 09:08 UTC, podlovchenko commented on src/utils/query-stringify.ts
> +export function queryStringify(data: {} | undefined) {
```suggestion
export function queryStringify(data?: object) {
```

2022-04-25 13:59 UTC, Danilov-Andrey commented on babel.config.js
> +  presets: ["@babel/preset-env","@babel/preset-typescript"],
я пока не знаю как этот ворнинг исправить, если убрать этот пресет - тесты не запускаются. я подробнее бы посмотрел на неделе доработок.

2022-04-25 18:07 UTC, Danilov-Andrey commented
Поправил замечания, tsc где смог поправил, в остальных местах оставил туду. Пофиксить релоад в нетлифай не получилось, там вроде нельзя экспресс развернуть, это в хероку в 4 спринте будет работать. Форматирование тоже поправил.

2022-04-25 18:28 UTC, podlovchenko commented
https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router
Попробуй добавить в netlify.toml
`[[redirects]]
  from = "/*"
  to = "/"
  status = 200`
или создать файл _redirects

2022-04-25 18:56 UTC, Danilov-Andrey commented
Да, так сработало. Спасибо.

2022-04-26 07:56 UTC, podlovchenko commented
Принимаю работу

2022-04-27 18:58 UTC, merged